name: Node CI

on: [push]

strategy:
  matrix:
    node: [8, 10]
    os: [windows-2016, ubuntu-14.04, ubuntu-18.04]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: npm install, build, and test
      run: |
        npm install -g typescript@2.9.2
        npm install -g mocha
        npm install
        npm run prepare
        npm run build --if-present
        npm run test-unit